--
-- PostgreSQL database dump
--

--
-- TOC entry 231 (class 1259 OID 17749)
-- Name: Addons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Addons" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "CateringCompanyId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


ALTER TABLE public."Addons" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17634)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17633)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17612)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17649)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17648)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17663)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17678)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17697)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17620)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17797)
-- Name: CateringCompanies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CateringCompanies" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."CateringCompanies" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17578)
-- Name: Dishes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Dishes" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "CateringCompanyId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


ALTER TABLE public."Dishes" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17760)
-- Name: GroupMembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GroupMembers" (
    "Id" uuid NOT NULL,
    "GroupId" uuid NOT NULL,
    "UserId" character varying(458) NOT NULL,
    "IsActive" boolean NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."GroupMembers" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17806)
-- Name: GroupPackageAssignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GroupPackageAssignments" (
    "Id" uuid NOT NULL,
    "GroupId" uuid NOT NULL,
    "PackageId" uuid NOT NULL,
    "ActiveFrom" timestamp with time zone NOT NULL,
    "ActiveTo" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."GroupPackageAssignments" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 18068)
-- Name: GroupSettlements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GroupSettlements" (
    "Id" uuid NOT NULL,
    "SettlementPeriodId" uuid NOT NULL,
    "GroupId" uuid NOT NULL,
    "OrdersCount" integer NOT NULL,
    "TotalAmount" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."GroupSettlements" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17601)
-- Name: Groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Groups" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "MemberCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CateringCompanyId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "CoordinatorUserId" character varying(458)
);


ALTER TABLE public."Groups" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17895)
-- Name: MenuDayAddons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MenuDayAddons" (
    "Id" uuid NOT NULL,
    "MenuDayId" uuid NOT NULL,
    "AddonId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."MenuDayAddons" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17880)
-- Name: MenuDays; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MenuDays" (
    "Id" uuid NOT NULL,
    "MenuPeriodId" uuid NOT NULL,
    "MenuDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."MenuDays" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17915)
-- Name: MenuItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MenuItems" (
    "Id" uuid NOT NULL,
    "MenuDayId" uuid NOT NULL,
    "DishId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."MenuItems" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17827)
-- Name: MenuPeriods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MenuPeriods" (
    "Id" uuid NOT NULL,
    "Name" character varying(120) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CateringCompanyId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."MenuPeriods" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17999)
-- Name: OrderAddons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderAddons" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "AddonId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."OrderAddons" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 18018)
-- Name: OrderStatusHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderStatusHistories" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "OrderStatusId" uuid NOT NULL,
    "ChangedByUserId" character varying(450),
    "ChangedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."OrderStatusHistories" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17958)
-- Name: OrderStatuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderStatuses" (
    "Id" uuid NOT NULL,
    "Name" character varying(80) NOT NULL,
    "IsFinal" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."OrderStatuses" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17968)
-- Name: Orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Orders" (
    "Id" uuid NOT NULL,
    "GroupMemberId" uuid NOT NULL,
    "MenuDayId" uuid NOT NULL,
    "DishId" uuid NOT NULL,
    "OrderStatusId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Orders" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17840)
-- Name: PackageAddons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PackageAddons" (
    "Id" uuid NOT NULL,
    "PackageId" uuid NOT NULL,
    "AddonId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."PackageAddons" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17860)
-- Name: PackageDishes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PackageDishes" (
    "Id" uuid NOT NULL,
    "PackageId" uuid NOT NULL,
    "DishId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."PackageDishes" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17782)
-- Name: Packages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Packages" (
    "Id" uuid NOT NULL,
    "Name" character varying(120) NOT NULL,
    "PricePerPerson" numeric(10,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CateringCompanyId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Packages" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 18180)
-- Name: PrintTemplates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PrintTemplates" (
    "Id" uuid NOT NULL,
    "Code" character varying(80) NOT NULL,
    "Name" character varying(160) NOT NULL,
    "TitleTemplate" character varying(500) NOT NULL,
    "BodyTemplate" character varying(3000) NOT NULL,
    "FooterTemplate" character varying(1000) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PrintTemplates" OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 18089)
-- Name: SettlementLines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SettlementLines" (
    "Id" uuid NOT NULL,
    "GroupSettlementId" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "PackagePrice" numeric(10,2) NOT NULL,
    "AddonsPrice" numeric(10,2) NOT NULL,
    "TotalPrice" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."SettlementLines" OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 18052)
-- Name: SettlementPeriods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SettlementPeriods" (
    "Id" uuid NOT NULL,
    "CateringCompanyId" uuid,
    "Name" character varying(150) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsClosed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."SettlementPeriods" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17571)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3838 (class 2606 OID 17759)
-- Name: Addons PK_Addons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addons"
    ADD CONSTRAINT "PK_Addons" PRIMARY KEY ("Id");


--
-- TOC entry 3824 (class 2606 OID 17642)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3816 (class 2606 OID 17619)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3827 (class 2606 OID 17657)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3830 (class 2606 OID 17672)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3833 (class 2606 OID 17686)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3835 (class 2606 OID 17706)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3820 (class 2606 OID 17632)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3847 (class 2606 OID 17805)
-- Name: CateringCompanies PK_CateringCompanies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CateringCompanies"
    ADD CONSTRAINT "PK_CateringCompanies" PRIMARY KEY ("Id");


--
-- TOC entry 3810 (class 2606 OID 17588)
-- Name: Dishes PK_Dishes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dishes"
    ADD CONSTRAINT "PK_Dishes" PRIMARY KEY ("Id");


--
-- TOC entry 3842 (class 2606 OID 17769)
-- Name: GroupMembers PK_GroupMembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "PK_GroupMembers" PRIMARY KEY ("Id");


--
-- TOC entry 3851 (class 2606 OID 17816)
-- Name: GroupPackageAssignments PK_GroupPackageAssignments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupPackageAssignments"
    ADD CONSTRAINT "PK_GroupPackageAssignments" PRIMARY KEY ("Id");


--
-- TOC entry 3898 (class 2606 OID 18078)
-- Name: GroupSettlements PK_GroupSettlements; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupSettlements"
    ADD CONSTRAINT "PK_GroupSettlements" PRIMARY KEY ("Id");


--
-- TOC entry 3814 (class 2606 OID 17611)
-- Name: Groups PK_Groups; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "PK_Groups" PRIMARY KEY ("Id");


--
-- TOC entry 3869 (class 2606 OID 17904)
-- Name: MenuDayAddons PK_MenuDayAddons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuDayAddons"
    ADD CONSTRAINT "PK_MenuDayAddons" PRIMARY KEY ("Id");


--
-- TOC entry 3865 (class 2606 OID 17889)
-- Name: MenuDays PK_MenuDays; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuDays"
    ADD CONSTRAINT "PK_MenuDays" PRIMARY KEY ("Id");


--
-- TOC entry 3873 (class 2606 OID 17924)
-- Name: MenuItems PK_MenuItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuItems"
    ADD CONSTRAINT "PK_MenuItems" PRIMARY KEY ("Id");


--
-- TOC entry 3854 (class 2606 OID 17839)
-- Name: MenuPeriods PK_MenuPeriods; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuPeriods"
    ADD CONSTRAINT "PK_MenuPeriods" PRIMARY KEY ("Id");


--
-- TOC entry 3886 (class 2606 OID 18007)
-- Name: OrderAddons PK_OrderAddons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderAddons"
    ADD CONSTRAINT "PK_OrderAddons" PRIMARY KEY ("Id");


--
-- TOC entry 3891 (class 2606 OID 18026)
-- Name: OrderStatusHistories PK_OrderStatusHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderStatusHistories"
    ADD CONSTRAINT "PK_OrderStatusHistories" PRIMARY KEY ("Id");


--
-- TOC entry 3876 (class 2606 OID 17967)
-- Name: OrderStatuses PK_OrderStatuses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderStatuses"
    ADD CONSTRAINT "PK_OrderStatuses" PRIMARY KEY ("Id");


--
-- TOC entry 3882 (class 2606 OID 17978)
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- TOC entry 3858 (class 2606 OID 17849)
-- Name: PackageAddons PK_PackageAddons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PackageAddons"
    ADD CONSTRAINT "PK_PackageAddons" PRIMARY KEY ("Id");


--
-- TOC entry 3862 (class 2606 OID 17869)
-- Name: PackageDishes PK_PackageDishes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PackageDishes"
    ADD CONSTRAINT "PK_PackageDishes" PRIMARY KEY ("Id");


--
-- TOC entry 3845 (class 2606 OID 17790)
-- Name: Packages PK_Packages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "PK_Packages" PRIMARY KEY ("Id");


--
-- TOC entry 3905 (class 2606 OID 18195)
-- Name: PrintTemplates PK_PrintTemplates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrintTemplates"
    ADD CONSTRAINT "PK_PrintTemplates" PRIMARY KEY ("Id");


--
-- TOC entry 3902 (class 2606 OID 18100)
-- Name: SettlementLines PK_SettlementLines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SettlementLines"
    ADD CONSTRAINT "PK_SettlementLines" PRIMARY KEY ("Id");


--
-- TOC entry 3894 (class 2606 OID 18062)
-- Name: SettlementPeriods PK_SettlementPeriods; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SettlementPeriods"
    ADD CONSTRAINT "PK_SettlementPeriods" PRIMARY KEY ("Id");


--
-- TOC entry 3807 (class 2606 OID 17577)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3818 (class 1259 OID 17717)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3836 (class 1259 OID 18141)
-- Name: IX_Addons_CateringCompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Addons_CateringCompanyId" ON public."Addons" USING btree ("CateringCompanyId");


--
-- TOC entry 3822 (class 1259 OID 17712)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3825 (class 1259 OID 17714)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3828 (class 1259 OID 17715)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3831 (class 1259 OID 17716)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3808 (class 1259 OID 18140)
-- Name: IX_Dishes_CateringCompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Dishes_CateringCompanyId" ON public."Dishes" USING btree ("CateringCompanyId");


--
-- TOC entry 3839 (class 1259 OID 17780)
-- Name: IX_GroupMembers_GroupId_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_GroupMembers_GroupId_UserId" ON public."GroupMembers" USING btree ("GroupId", "UserId");


--
-- TOC entry 3840 (class 1259 OID 17781)
-- Name: IX_GroupMembers_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GroupMembers_UserId" ON public."GroupMembers" USING btree ("UserId");


--
-- TOC entry 3848 (class 1259 OID 17937)
-- Name: IX_GroupPackageAssignments_GroupId_PackageId_ActiveFrom; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_GroupPackageAssignments_GroupId_PackageId_ActiveFrom" ON public."GroupPackageAssignments" USING btree ("GroupId", "PackageId", "ActiveFrom");


--
-- TOC entry 3849 (class 1259 OID 17938)
-- Name: IX_GroupPackageAssignments_PackageId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GroupPackageAssignments_PackageId" ON public."GroupPackageAssignments" USING btree ("PackageId");


--
-- TOC entry 3895 (class 1259 OID 18111)
-- Name: IX_GroupSettlements_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GroupSettlements_GroupId" ON public."GroupSettlements" USING btree ("GroupId");


--
-- TOC entry 3896 (class 1259 OID 18112)
-- Name: IX_GroupSettlements_SettlementPeriodId_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_GroupSettlements_SettlementPeriodId_GroupId" ON public."GroupSettlements" USING btree ("SettlementPeriodId", "GroupId");


--
-- TOC entry 3811 (class 1259 OID 17936)
-- Name: IX_Groups_CateringCompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Groups_CateringCompanyId" ON public."Groups" USING btree ("CateringCompanyId");


--
-- TOC entry 3812 (class 1259 OID 18199)
-- Name: IX_Groups_CoordinatorUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Groups_CoordinatorUserId" ON public."Groups" USING btree ("CoordinatorUserId");


--
-- TOC entry 3866 (class 1259 OID 17939)
-- Name: IX_MenuDayAddons_AddonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MenuDayAddons_AddonId" ON public."MenuDayAddons" USING btree ("AddonId");


--
-- TOC entry 3867 (class 1259 OID 17940)
-- Name: IX_MenuDayAddons_MenuDayId_AddonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_MenuDayAddons_MenuDayId_AddonId" ON public."MenuDayAddons" USING btree ("MenuDayId", "AddonId");


--
-- TOC entry 3863 (class 1259 OID 17941)
-- Name: IX_MenuDays_MenuPeriodId_MenuDate; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_MenuDays_MenuPeriodId_MenuDate" ON public."MenuDays" USING btree ("MenuPeriodId", "MenuDate");


--
-- TOC entry 3870 (class 1259 OID 17942)
-- Name: IX_MenuItems_DishId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MenuItems_DishId" ON public."MenuItems" USING btree ("DishId");


--
-- TOC entry 3871 (class 1259 OID 17943)
-- Name: IX_MenuItems_MenuDayId_DishId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_MenuItems_MenuDayId_DishId" ON public."MenuItems" USING btree ("MenuDayId", "DishId");


--
-- TOC entry 3852 (class 1259 OID 18139)
-- Name: IX_MenuPeriods_CateringCompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MenuPeriods_CateringCompanyId" ON public."MenuPeriods" USING btree ("CateringCompanyId");


--
-- TOC entry 3883 (class 1259 OID 18042)
-- Name: IX_OrderAddons_AddonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderAddons_AddonId" ON public."OrderAddons" USING btree ("AddonId");


--
-- TOC entry 3884 (class 1259 OID 18043)
-- Name: IX_OrderAddons_OrderId_AddonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_OrderAddons_OrderId_AddonId" ON public."OrderAddons" USING btree ("OrderId", "AddonId");


--
-- TOC entry 3887 (class 1259 OID 18049)
-- Name: IX_OrderStatusHistories_ChangedByUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderStatusHistories_ChangedByUserId" ON public."OrderStatusHistories" USING btree ("ChangedByUserId");


--
-- TOC entry 3888 (class 1259 OID 18050)
-- Name: IX_OrderStatusHistories_OrderId_ChangedAt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderStatusHistories_OrderId_ChangedAt" ON public."OrderStatusHistories" USING btree ("OrderId", "ChangedAt");


--
-- TOC entry 3889 (class 1259 OID 18051)
-- Name: IX_OrderStatusHistories_OrderStatusId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderStatusHistories_OrderStatusId" ON public."OrderStatusHistories" USING btree ("OrderStatusId");


--
-- TOC entry 3874 (class 1259 OID 18048)
-- Name: IX_OrderStatuses_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_OrderStatuses_Name" ON public."OrderStatuses" USING btree ("Name");


--
-- TOC entry 3877 (class 1259 OID 18044)
-- Name: IX_Orders_DishId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orders_DishId" ON public."Orders" USING btree ("DishId");


--
-- TOC entry 3878 (class 1259 OID 18045)
-- Name: IX_Orders_GroupMemberId_MenuDayId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Orders_GroupMemberId_MenuDayId" ON public."Orders" USING btree ("GroupMemberId", "MenuDayId");


--
-- TOC entry 3879 (class 1259 OID 18046)
-- Name: IX_Orders_MenuDayId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orders_MenuDayId" ON public."Orders" USING btree ("MenuDayId");


--
-- TOC entry 3880 (class 1259 OID 18047)
-- Name: IX_Orders_OrderStatusId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orders_OrderStatusId" ON public."Orders" USING btree ("OrderStatusId");


--
-- TOC entry 3855 (class 1259 OID 17944)
-- Name: IX_PackageAddons_AddonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PackageAddons_AddonId" ON public."PackageAddons" USING btree ("AddonId");


--
-- TOC entry 3856 (class 1259 OID 17945)
-- Name: IX_PackageAddons_PackageId_AddonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PackageAddons_PackageId_AddonId" ON public."PackageAddons" USING btree ("PackageId", "AddonId");


--
-- TOC entry 3859 (class 1259 OID 17946)
-- Name: IX_PackageDishes_DishId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PackageDishes_DishId" ON public."PackageDishes" USING btree ("DishId");


--
-- TOC entry 3860 (class 1259 OID 17947)
-- Name: IX_PackageDishes_PackageId_DishId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PackageDishes_PackageId_DishId" ON public."PackageDishes" USING btree ("PackageId", "DishId");


--
-- TOC entry 3843 (class 1259 OID 17935)
-- Name: IX_Packages_CateringCompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Packages_CateringCompanyId" ON public."Packages" USING btree ("CateringCompanyId");


--
-- TOC entry 3903 (class 1259 OID 18196)
-- Name: IX_PrintTemplates_Code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PrintTemplates_Code" ON public."PrintTemplates" USING btree ("Code");


--
-- TOC entry 3899 (class 1259 OID 18113)
-- Name: IX_SettlementLines_GroupSettlementId_OrderId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_SettlementLines_GroupSettlementId_OrderId" ON public."SettlementLines" USING btree ("GroupSettlementId", "OrderId");


--
-- TOC entry 3900 (class 1259 OID 18114)
-- Name: IX_SettlementLines_OrderId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SettlementLines_OrderId" ON public."SettlementLines" USING btree ("OrderId");


--
-- TOC entry 3892 (class 1259 OID 18115)
-- Name: IX_SettlementPeriods_CateringCompanyId_StartDate_EndDate; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_SettlementPeriods_CateringCompanyId_StartDate_EndDate" ON public."SettlementPeriods" USING btree ("CateringCompanyId", "StartDate", "EndDate");


--
-- TOC entry 3817 (class 1259 OID 17713)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3821 (class 1259 OID 17718)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3915 (class 2606 OID 18142)
-- Name: Addons FK_Addons_CateringCompanies_CateringCompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addons"
    ADD CONSTRAINT "FK_Addons_CateringCompanies_CateringCompanyId" FOREIGN KEY ("CateringCompanyId") REFERENCES public."CateringCompanies"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3909 (class 2606 OID 17643)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3910 (class 2606 OID 17658)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3911 (class 2606 OID 17673)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3912 (class 2606 OID 17687)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3913 (class 2606 OID 17692)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3914 (class 2606 OID 17707)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3906 (class 2606 OID 18147)
-- Name: Dishes FK_Dishes_CateringCompanies_CateringCompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dishes"
    ADD CONSTRAINT "FK_Dishes_CateringCompanies_CateringCompanyId" FOREIGN KEY ("CateringCompanyId") REFERENCES public."CateringCompanies"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3916 (class 2606 OID 17770)
-- Name: GroupMembers FK_GroupMembers_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3917 (class 2606 OID 17775)
-- Name: GroupMembers FK_GroupMembers_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- TOC entry 3919 (class 2606 OID 17817)
-- Name: GroupPackageAssignments FK_GroupPackageAssignments_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupPackageAssignments"
    ADD CONSTRAINT "FK_GroupPackageAssignments_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- TOC entry 3920 (class 2606 OID 17822)
-- Name: GroupPackageAssignments FK_GroupPackageAssignments_Packages_PackageId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupPackageAssignments"
    ADD CONSTRAINT "FK_GroupPackageAssignments_Packages_PackageId" FOREIGN KEY ("PackageId") REFERENCES public."Packages"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3941 (class 2606 OID 18079)
-- Name: GroupSettlements FK_GroupSettlements_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupSettlements"
    ADD CONSTRAINT "FK_GroupSettlements_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3942 (class 2606 OID 18084)
-- Name: GroupSettlements FK_GroupSettlements_SettlementPeriods_SettlementPeriodId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GroupSettlements"
    ADD CONSTRAINT "FK_GroupSettlements_SettlementPeriods_SettlementPeriodId" FOREIGN KEY ("SettlementPeriodId") REFERENCES public."SettlementPeriods"("Id") ON DELETE CASCADE;


--
-- TOC entry 3907 (class 2606 OID 18200)
-- Name: Groups FK_Groups_AspNetUsers_CoordinatorUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "FK_Groups_AspNetUsers_CoordinatorUserId" FOREIGN KEY ("CoordinatorUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3908 (class 2606 OID 17948)
-- Name: Groups FK_Groups_CateringCompanies_CateringCompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "FK_Groups_CateringCompanies_CateringCompanyId" FOREIGN KEY ("CateringCompanyId") REFERENCES public."CateringCompanies"("Id") ON DELETE CASCADE;


--
-- TOC entry 3927 (class 2606 OID 17905)
-- Name: MenuDayAddons FK_MenuDayAddons_Addons_AddonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuDayAddons"
    ADD CONSTRAINT "FK_MenuDayAddons_Addons_AddonId" FOREIGN KEY ("AddonId") REFERENCES public."Addons"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3928 (class 2606 OID 17910)
-- Name: MenuDayAddons FK_MenuDayAddons_MenuDays_MenuDayId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuDayAddons"
    ADD CONSTRAINT "FK_MenuDayAddons_MenuDays_MenuDayId" FOREIGN KEY ("MenuDayId") REFERENCES public."MenuDays"("Id") ON DELETE CASCADE;


--
-- TOC entry 3926 (class 2606 OID 17890)
-- Name: MenuDays FK_MenuDays_MenuPeriods_MenuPeriodId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuDays"
    ADD CONSTRAINT "FK_MenuDays_MenuPeriods_MenuPeriodId" FOREIGN KEY ("MenuPeriodId") REFERENCES public."MenuPeriods"("Id") ON DELETE CASCADE;


--
-- TOC entry 3929 (class 2606 OID 17925)
-- Name: MenuItems FK_MenuItems_Dishes_DishId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuItems"
    ADD CONSTRAINT "FK_MenuItems_Dishes_DishId" FOREIGN KEY ("DishId") REFERENCES public."Dishes"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3930 (class 2606 OID 17930)
-- Name: MenuItems FK_MenuItems_MenuDays_MenuDayId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuItems"
    ADD CONSTRAINT "FK_MenuItems_MenuDays_MenuDayId" FOREIGN KEY ("MenuDayId") REFERENCES public."MenuDays"("Id") ON DELETE CASCADE;


--
-- TOC entry 3921 (class 2606 OID 18152)
-- Name: MenuPeriods FK_MenuPeriods_CateringCompanies_CateringCompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MenuPeriods"
    ADD CONSTRAINT "FK_MenuPeriods_CateringCompanies_CateringCompanyId" FOREIGN KEY ("CateringCompanyId") REFERENCES public."CateringCompanies"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3935 (class 2606 OID 18008)
-- Name: OrderAddons FK_OrderAddons_Addons_AddonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderAddons"
    ADD CONSTRAINT "FK_OrderAddons_Addons_AddonId" FOREIGN KEY ("AddonId") REFERENCES public."Addons"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3936 (class 2606 OID 18013)
-- Name: OrderAddons FK_OrderAddons_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderAddons"
    ADD CONSTRAINT "FK_OrderAddons_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- TOC entry 3937 (class 2606 OID 18027)
-- Name: OrderStatusHistories FK_OrderStatusHistories_AspNetUsers_ChangedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderStatusHistories"
    ADD CONSTRAINT "FK_OrderStatusHistories_AspNetUsers_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3938 (class 2606 OID 18032)
-- Name: OrderStatusHistories FK_OrderStatusHistories_OrderStatuses_OrderStatusId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderStatusHistories"
    ADD CONSTRAINT "FK_OrderStatusHistories_OrderStatuses_OrderStatusId" FOREIGN KEY ("OrderStatusId") REFERENCES public."OrderStatuses"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3939 (class 2606 OID 18037)
-- Name: OrderStatusHistories FK_OrderStatusHistories_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderStatusHistories"
    ADD CONSTRAINT "FK_OrderStatusHistories_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- TOC entry 3931 (class 2606 OID 17979)
-- Name: Orders FK_Orders_Dishes_DishId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_Dishes_DishId" FOREIGN KEY ("DishId") REFERENCES public."Dishes"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3932 (class 2606 OID 17984)
-- Name: Orders FK_Orders_GroupMembers_GroupMemberId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_GroupMembers_GroupMemberId" FOREIGN KEY ("GroupMemberId") REFERENCES public."GroupMembers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3933 (class 2606 OID 17989)
-- Name: Orders FK_Orders_MenuDays_MenuDayId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_MenuDays_MenuDayId" FOREIGN KEY ("MenuDayId") REFERENCES public."MenuDays"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3934 (class 2606 OID 17994)
-- Name: Orders FK_Orders_OrderStatuses_OrderStatusId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_OrderStatuses_OrderStatusId" FOREIGN KEY ("OrderStatusId") REFERENCES public."OrderStatuses"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3922 (class 2606 OID 17850)
-- Name: PackageAddons FK_PackageAddons_Addons_AddonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PackageAddons"
    ADD CONSTRAINT "FK_PackageAddons_Addons_AddonId" FOREIGN KEY ("AddonId") REFERENCES public."Addons"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3923 (class 2606 OID 17855)
-- Name: PackageAddons FK_PackageAddons_Packages_PackageId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PackageAddons"
    ADD CONSTRAINT "FK_PackageAddons_Packages_PackageId" FOREIGN KEY ("PackageId") REFERENCES public."Packages"("Id") ON DELETE CASCADE;


--
-- TOC entry 3924 (class 2606 OID 17870)
-- Name: PackageDishes FK_PackageDishes_Dishes_DishId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PackageDishes"
    ADD CONSTRAINT "FK_PackageDishes_Dishes_DishId" FOREIGN KEY ("DishId") REFERENCES public."Dishes"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3925 (class 2606 OID 17875)
-- Name: PackageDishes FK_PackageDishes_Packages_PackageId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PackageDishes"
    ADD CONSTRAINT "FK_PackageDishes_Packages_PackageId" FOREIGN KEY ("PackageId") REFERENCES public."Packages"("Id") ON DELETE CASCADE;


--
-- TOC entry 3918 (class 2606 OID 17953)
-- Name: Packages FK_Packages_CateringCompanies_CateringCompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "FK_Packages_CateringCompanies_CateringCompanyId" FOREIGN KEY ("CateringCompanyId") REFERENCES public."CateringCompanies"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3943 (class 2606 OID 18101)
-- Name: SettlementLines FK_SettlementLines_GroupSettlements_GroupSettlementId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SettlementLines"
    ADD CONSTRAINT "FK_SettlementLines_GroupSettlements_GroupSettlementId" FOREIGN KEY ("GroupSettlementId") REFERENCES public."GroupSettlements"("Id") ON DELETE CASCADE;


--
-- TOC entry 3944 (class 2606 OID 18106)
-- Name: SettlementLines FK_SettlementLines_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SettlementLines"
    ADD CONSTRAINT "FK_SettlementLines_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3940 (class 2606 OID 18063)
-- Name: SettlementPeriods FK_SettlementPeriods_CateringCompanies_CateringCompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SettlementPeriods"
    ADD CONSTRAINT "FK_SettlementPeriods_CateringCompanies_CateringCompanyId" FOREIGN KEY ("CateringCompanyId") REFERENCES public."CateringCompanies"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--
